# Generated by Django 4.0.1 on 2024-02-17 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0002_anagrammanagement_anagramtable_imageseqmanagement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anagrammanagement',
            name='description',
        ),
    ]
