# Generated by Django 4.0.1 on 2024-02-17 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0003_remove_anagrammanagement_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='anagrammanagement',
            name='level',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
