# Generated by Django 4.0.1 on 2024-02-21 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0004_anagrammanagement_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='storymanagement',
            name='image',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
